apiVersion: v1
kind: ConfigMap
metadata:
  name: postgress-write-config
data:
  POSTGRESQL_USERNAME: postgres
  POSTGRESQL_PASSWORD: heydurgesh
  POSTGRESQL_REPLICATION_USER: postgres
  POSTGRESQL_REPLICATION_PASSWORD: heydurgesh
  POSTGRESQL_REPLICATION_MODE: master
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: postgress-read-config
data:
  POSTGRESQL_USERNAME: postgres
  POSTGRESQL_PASSWORD: heydurgesh
  POSTGRESQL_REPLICATION_USER: postgres
  POSTGRESQL_REPLICATION_PASSWORD: heydurgesh
  POSTGRESQL_REPLICATION_MODE: slave
  POSTGRESQL_MASTER_HOST: postgres-write.63d.svc.cluster.local
  POSTGRESQL_MASTER_PORT_NUMBER: "5432"