apiVersion: v1
kind: Service
metadata:
  name: postgres-write
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    postgresfunction: write
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-read
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    postgresfunction: read
  type: ClusterIP